# Generated by Django 5.0.6 on 2024-07-18 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='Unknown', max_length=40)),
                ('Student_bio', models.TextField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_nationality', models.CharField(max_length=20)),
                ('date_of_birth', models.DateTimeField(blank=True, verbose_name=datetime.date)),
                ('student_Guardian', models.CharField(max_length=40)),
                ('student_class', models.CharField(max_length=20)),
                ('student_mentor', models.CharField(max_length=40)),
            ],
        ),
    ]
